# Generated by Django 6.0.7 on 2026-07-31 16:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="auditlog",
            table="audit_log",
        ),
    ]
