# Generated by Django 6.0.7 on 2026-08-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_auditlog_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("invited", "Invited"),
                    ("accepted", "Accepted"),
                    ("password_reset", "Password Reset"),
                    ("remove", "Remove"),
                    ("leave", "Leave"),
                ],
                max_length=20,
            ),
        ),
    ]
