# Generated by Django 6.0.7 on 2026-08-03 01:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_auditlog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="model_name",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("group", "Group"),
                    ("group_membership", "Group Membership"),
                    ("group_invitation", "Group Invitation"),
                    ("category", "Category"),
                    ("expense", "Expense"),
                    ("expense_payer", "Expense Payer"),
                    ("expense_participant", "Expense Participant"),
                    ("settlement", "Settlement"),
                ],
                max_length=50,
            ),
        ),
    ]
