# Generated by Django 6.0.7 on 2026-07-25 15:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="category",
            table="expenes_category",
        ),
    ]
