# Generated by Django 6.0.7 on 2026-07-25 15:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0002_alter_category_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="category",
            table="expense_category",
        ),
    ]
