# Generated by Django 6.0.7 on 2026-07-31 06:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0003_alter_category_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="amount",
            field=models.DecimalField(
                decimal_places=5,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(1.0)],
            ),
        ),
    ]
