# Generated by Django 6.0.7 on 2026-07-31 06:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0004_alter_expense_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenseparticipant",
            name="amount_to_pay",
            field=models.DecimalField(
                decimal_places=5,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="expensepayer",
            name="amount_paid",
            field=models.DecimalField(
                decimal_places=5,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(1.0)],
            ),
        ),
    ]
