# Generated by Django 6.0.7 on 2026-07-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0005_alter_expenseparticipant_amount_to_pay_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
