# Generated by Django 6.0.7 on 2026-08-03 01:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0006_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
