# Generated by Django 6.0.7 on 2026-10-01 06:19

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_alter_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=5, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00001'))]),
        ),
        migrations.AlterField(
            model_name='expensepayer',
            name='amount_paid',
            field=models.DecimalField(decimal_places=5, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00001'))]),
        ),
    ]
