# Generated by Django 6.0.7 on 2026-08-02 14:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("settlements", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="settlement",
            name="status",
        ),
    ]
