# Generated by Django 6.0.7 on 2026-07-29 05:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0002_groupinvitation"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="groupinvitation",
            name="unique_pending_group_invitation",
        ),
    ]
