# Generated by Django 6.0.7 on 2026-07-30 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0003_remove_groupinvitation_unique_pending_group_invitation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="group_imagekey",
            field=models.ImageField(blank=True, null=True, upload_to="groups/"),
        ),
    ]
