# Generated by Django 6.0.7 on 2026-08-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0004_alter_group_group_imagekey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="group_imagekey",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
